# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-mega-linter
  description: Linter for terraform, golang, markdown and yaml code
  homepage: https://cloudposse.com/accelerate
  topics: ""
