name: "Mega-Linter"
description: "A GitHub Action to lint terraform, golang, markdown and yaml code."
author: Cloud Posse <hello@cloudposse.com>
branding:
  icon: cloud-lightning
  color: blue
inputs:
  githubToken:
    description: "The GitHub token to use for authentication."
    required: true

  golangReporter:
    required: true
    description: The reviewdog reporter to use for golang code.
    default: "github-pr-check"

  golangSourceDir:
    required: true
    description: The directory containing the source code to test
    default: "."

runs:
  using: composite

  steps:
    - name: Invoke workflow without inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Run Linting Checks
        token: ${{ inputs.githubToken }}
        inputs:
          '{ "githubToken": "${{ inputs.githubToken }}", "golangReporter": "github-pr-check", "golangSourceDir":
          "test/src" }'
