name: "Mega-Linter"
description: "A GitHub Action to lint terraform, golang, markdown and yaml code."
author: Cloud Posse <hello@cloudposse.com>
branding:
  icon: cloud-lightning
  color: blue
inputs:
  githubToken:
    description: "The GitHub token to use for authentication."
    required: true
  golangReporter:
    required: true
    description: The reviewdog reporter to use for golang code.
    default: "github-pr-check"
  golangSourceDir:
    required: true
    description: The directory containing the source code to test
    default: "."
  golangEnabled:
    description: "Whether to run golang linting checks."
    required: true
    default: "true"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: reviewdog/action-golangci-lint@v2
      if: ${{ inputs.golangEnabled == 'true' }}
      with:
        github_token: ${{ inputs.githubToken }}
        golangci_lint_flags: --timeout 5m
        reporter: ${{ inputs.golangReporter }}
        workdir: ${{ inputs.golangSourceDir }}
        fail_on_error: true
        filter_mode: nofilter
