name: Run Linting Checks

on:
  pull_request:
  workflow_dispatch:
    inputs:
      githubToken:
        description: "The GitHub token to use for authentication."
        required: true
      golangEnabled:
        description: "Whether to run golang linting checks."
        required: true
        default: "true"
      golangReporter:
        required: true
        description: The reviewdog reporter to use for golang code.
        default: "github-pr-check"
      golangSourceDir:
        required: true
        description: The directory containing the source code to test
        default: "."

jobs:
  golang:
    if: ${{ github.event.inputs.golangEnabled == 'true' }}
    name: reviewdog/golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ github.event.inputs.githubToken }}
          golangci_lint_flags: --timeout 5m
          reporter: ${{ github.event.inputs.golangReporter }}
          workdir: ${{ github.event.inputs.golangSourceDir }}
          fail_on_error: true
          filter_mode: nofilter
